version: '3.9'

services:
  schema-dump:
    image: postgres:17-alpine
    container_name: smartbussing_schema_dump
    environment:
      PG_DB_URL: ${PG_DB_URL}
    volumes:
      - ./database:/database
    command: >
      sh -c "PGSSLMODE=require pg_dump --schema-only --schema=public \"$$PG_DB_URL\" | grep -v 'CREATE SCHEMA public' > /database/schema_backup.sql && echo 'Schema dump complete.'"

  postgres-test:
    image: postgres:17-alpine
    container_name: smartbussing_test_container
    depends_on:
      schema-dump:
        condition: service_completed_successfully

    environment:
      POSTGRES_DB: smartbuss_test
      POSTGRES_USER: smartbusser
      POSTGRES_PASSWORD: bussword

    ports:
      - "5433:5432"

    volumes:
      - ./database/schema_backup.sql:/docker-entrypoint-initdb.d/01-schema.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartbusser -d smartbuss_test"]
      interval: 2s
      timeout: 5s
      retries: 5