SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."contrato" (
    "id_contrato" integer NOT NULL,
    "fecha_fin" timestamp(6) without time zone,
    "fecha_inicio" timestamp(6) without time zone,
    "monto" integer NOT NULL
);


ALTER TABLE "public"."contrato" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."contrato_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."contrato_sequence" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."coordenada_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."coordenada_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."coordenadas" (
    "id_coordenada" integer NOT NULL,
    "latitud" double precision,
    "longitud" double precision
);


ALTER TABLE "public"."coordenadas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."coordenadas_ruta" (
    "ruta_id" integer NOT NULL,
    "coordenadas_id" integer NOT NULL
);


ALTER TABLE "public"."coordenadas_ruta" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."empresa" (
    "id_empresa" integer NOT NULL,
    "email" character varying(255),
    "metodo_pago" character varying(255),
    "name" character varying(255),
    "pais" character varying(255)
);


ALTER TABLE "public"."empresa" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."empresa_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."empresa_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."file_data" (
    "id_image" integer NOT NULL,
    "file_name" character varying(255),
    "path" character varying(255),
    "type" character varying(255),
    "image_id" integer
);


ALTER TABLE "public"."file_data" OWNER TO "postgres";


ALTER TABLE "public"."file_data" ALTER COLUMN "id_image" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."file_data_id_image_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."interesado" (
    "email" character varying(255) NOT NULL
);


ALTER TABLE "public"."interesado" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."interesado_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."interesado_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."lugar" (
    "lugar_id" integer NOT NULL,
    "descripcion" character varying(255),
    "name" character varying(255),
    "telefono" character varying(255),
    "tipo" character varying(255),
    "lugar_contrato_id" integer,
    "lugar_empresa_id" integer,
    "lugar_contr|ato_id" integer,
    "url_files" character varying(255)[]
);


ALTER TABLE "public"."lugar" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."lugar_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."lugar_sequence" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."microbus_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."microbus_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."parada" (
    "id_parada" integer NOT NULL,
    "nombre_parada" character varying(255),
    "coordenadas_parada_id_coordenada" integer,
    "descripcion_parada" character varying(255)
);


ALTER TABLE "public"."parada" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."parada_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."parada_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reporte_ruta" (
    "id_reporte_ruta" integer NOT NULL,
    "descripcion" character varying(255),
    "like_route" integer NOT NULL,
    "ruta_id" integer,
    "usuario_id" integer,
    "url_photos" character varying(255)[]
);


ALTER TABLE "public"."reporte_ruta" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."reporte_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."reporte_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ruta" (
    "id_ruta" integer NOT NULL,
    "active" boolean NOT NULL,
    "horario_ruta" character varying(255),
    "nombre_ruta" character varying(255),
    "color_ruta" character varying(255),
    "color_texto_ruta" character varying(255),
    "nombre_corto_ruta" character varying(255),
    "tipo_ruta" character varying(255)
);


ALTER TABLE "public"."ruta" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ruta_parada" (
    "id_ruta" integer NOT NULL,
    "id_parada" integer NOT NULL
);


ALTER TABLE "public"."ruta_parada" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ruta_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ruta_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."usuario" (
    "id_usuario" integer NOT NULL,
    "email" character varying(255),
    "nombre" character varying(255),
    "password" character varying(255),
    "profile_photourl" character varying(255)
);


ALTER TABLE "public"."usuario" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."usuario_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."usuario_sequence" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."viaje" (
    "id_viaje" integer NOT NULL,
    "costo_viaje" double precision NOT NULL,
    "tiempo_viaje" integer NOT NULL
);


ALTER TABLE "public"."viaje" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."viaje_parada" (
    "id_viaje" integer NOT NULL,
    "id_parada" integer NOT NULL
);


ALTER TABLE "public"."viaje_parada" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."viaje_ruta" (
    "id_viaje" integer NOT NULL,
    "id_ruta" integer NOT NULL
);


ALTER TABLE "public"."viaje_ruta" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."viaje_sequence"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."viaje_sequence" OWNER TO "postgres";


ALTER TABLE ONLY "public"."contrato"
    ADD CONSTRAINT "contrato_pkey" PRIMARY KEY ("id_contrato");



ALTER TABLE ONLY "public"."coordenadas"
    ADD CONSTRAINT "coordenadas_pkey" PRIMARY KEY ("id_coordenada");



ALTER TABLE ONLY "public"."empresa"
    ADD CONSTRAINT "empresa_pkey" PRIMARY KEY ("id_empresa");



ALTER TABLE ONLY "public"."file_data"
    ADD CONSTRAINT "file_data_pkey" PRIMARY KEY ("id_image");



ALTER TABLE ONLY "public"."interesado"
    ADD CONSTRAINT "interesado_pkey" PRIMARY KEY ("email");



ALTER TABLE ONLY "public"."lugar"
    ADD CONSTRAINT "lugar_pkey" PRIMARY KEY ("lugar_id");



ALTER TABLE ONLY "public"."parada"
    ADD CONSTRAINT "parada_pkey" PRIMARY KEY ("id_parada");



ALTER TABLE ONLY "public"."reporte_ruta"
    ADD CONSTRAINT "reporte_ruta_pkey" PRIMARY KEY ("id_reporte_ruta");



ALTER TABLE ONLY "public"."ruta"
    ADD CONSTRAINT "ruta_pkey" PRIMARY KEY ("id_ruta");



ALTER TABLE ONLY "public"."parada"
    ADD CONSTRAINT "ukmkrs0w9xcn08tai3ermubgvwt" UNIQUE ("coordenadas_parada_id_coordenada");



ALTER TABLE ONLY "public"."usuario"
    ADD CONSTRAINT "usuario_pkey" PRIMARY KEY ("id_usuario");



ALTER TABLE ONLY "public"."viaje"
    ADD CONSTRAINT "viaje_pkey" PRIMARY KEY ("id_viaje");



ALTER TABLE ONLY "public"."lugar"
    ADD CONSTRAINT "fk11u76n5iepy6svquy3v72u6h4" FOREIGN KEY ("lugar_empresa_id") REFERENCES "public"."empresa"("id_empresa");



ALTER TABLE ONLY "public"."lugar"
    ADD CONSTRAINT "fk52266vsw4x2k3erkn93qm49gy" FOREIGN KEY ("lugar_contr|ato_id") REFERENCES "public"."contrato"("id_contrato");



ALTER TABLE ONLY "public"."coordenadas_ruta"
    ADD CONSTRAINT "fk61plw9sskv924scfc9w8tnei9" FOREIGN KEY ("coordenadas_id") REFERENCES "public"."coordenadas"("id_coordenada");



ALTER TABLE ONLY "public"."file_data"
    ADD CONSTRAINT "fk98bwygluuydeujndx298f3gm2" FOREIGN KEY ("image_id") REFERENCES "public"."lugar"("lugar_id");



ALTER TABLE ONLY "public"."ruta_parada"
    ADD CONSTRAINT "fk9sv2hvx3ocwtrs62alemcwhf6" FOREIGN KEY ("id_parada") REFERENCES "public"."parada"("id_parada");



ALTER TABLE ONLY "public"."reporte_ruta"
    ADD CONSTRAINT "fkd28t0pheqtn3ebr8uy162jnj5" FOREIGN KEY ("ruta_id") REFERENCES "public"."ruta"("id_ruta");



ALTER TABLE ONLY "public"."coordenadas_ruta"
    ADD CONSTRAINT "fkelyn1hjj7w7prb806kwc9sx4b" FOREIGN KEY ("ruta_id") REFERENCES "public"."ruta"("id_ruta");



ALTER TABLE ONLY "public"."viaje_parada"
    ADD CONSTRAINT "fkf8dy9470e3y5v1moxbgdxhr93" FOREIGN KEY ("id_parada") REFERENCES "public"."parada"("id_parada");



ALTER TABLE ONLY "public"."viaje_parada"
    ADD CONSTRAINT "fkishneur6rlpj1m90dbbymjefo" FOREIGN KEY ("id_viaje") REFERENCES "public"."viaje"("id_viaje");



ALTER TABLE ONLY "public"."viaje_ruta"
    ADD CONSTRAINT "fkj7f1dv6fu4mc1csfqcqqmeab1" FOREIGN KEY ("id_viaje") REFERENCES "public"."viaje"("id_viaje");



ALTER TABLE ONLY "public"."ruta_parada"
    ADD CONSTRAINT "fkl58bg15ipt86jf2aqpb94v2bf" FOREIGN KEY ("id_ruta") REFERENCES "public"."ruta"("id_ruta");



ALTER TABLE ONLY "public"."parada"
    ADD CONSTRAINT "fkl74443u8ed4cirx4xmte9cjf6" FOREIGN KEY ("coordenadas_parada_id_coordenada") REFERENCES "public"."coordenadas"("id_coordenada");



ALTER TABLE ONLY "public"."viaje_ruta"
    ADD CONSTRAINT "fkrpqihtj1atq5padplnkv0s7rq" FOREIGN KEY ("id_ruta") REFERENCES "public"."ruta"("id_ruta");



ALTER TABLE ONLY "public"."lugar"
    ADD CONSTRAINT "fkrvi600giiy85kqbjo6n2sarjv" FOREIGN KEY ("lugar_contrato_id") REFERENCES "public"."contrato"("id_contrato");



ALTER TABLE ONLY "public"."reporte_ruta"
    ADD CONSTRAINT "fksjelqiqfoblq3le2ga7kaig6b" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id_usuario");



ALTER TABLE "public"."contrato" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."coordenadas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."coordenadas_ruta" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."empresa" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."interesado" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."lugar" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."parada" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reporte_ruta" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ruta" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ruta_parada" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."usuario" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."viaje" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."viaje_parada" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."viaje_ruta" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."contrato" TO "anon";
GRANT ALL ON TABLE "public"."contrato" TO "authenticated";
GRANT ALL ON TABLE "public"."contrato" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contrato_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."contrato_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contrato_sequence" TO "service_role";



GRANT ALL ON SEQUENCE "public"."coordenada_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."coordenada_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."coordenada_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."coordenadas" TO "anon";
GRANT ALL ON TABLE "public"."coordenadas" TO "authenticated";
GRANT ALL ON TABLE "public"."coordenadas" TO "service_role";



GRANT ALL ON TABLE "public"."coordenadas_ruta" TO "anon";
GRANT ALL ON TABLE "public"."coordenadas_ruta" TO "authenticated";
GRANT ALL ON TABLE "public"."coordenadas_ruta" TO "service_role";



GRANT ALL ON TABLE "public"."empresa" TO "anon";
GRANT ALL ON TABLE "public"."empresa" TO "authenticated";
GRANT ALL ON TABLE "public"."empresa" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."file_data" TO "anon";
GRANT ALL ON TABLE "public"."file_data" TO "authenticated";
GRANT ALL ON TABLE "public"."file_data" TO "service_role";



GRANT ALL ON SEQUENCE "public"."file_data_id_image_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."file_data_id_image_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."file_data_id_image_seq" TO "service_role";



GRANT ALL ON TABLE "public"."interesado" TO "anon";
GRANT ALL ON TABLE "public"."interesado" TO "authenticated";
GRANT ALL ON TABLE "public"."interesado" TO "service_role";



GRANT ALL ON SEQUENCE "public"."interesado_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."interesado_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."interesado_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."lugar" TO "anon";
GRANT ALL ON TABLE "public"."lugar" TO "authenticated";
GRANT ALL ON TABLE "public"."lugar" TO "service_role";



GRANT ALL ON SEQUENCE "public"."lugar_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."lugar_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."lugar_sequence" TO "service_role";



GRANT ALL ON SEQUENCE "public"."microbus_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."microbus_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."microbus_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."parada" TO "anon";
GRANT ALL ON TABLE "public"."parada" TO "authenticated";
GRANT ALL ON TABLE "public"."parada" TO "service_role";



GRANT ALL ON SEQUENCE "public"."parada_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."parada_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."parada_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."reporte_ruta" TO "anon";
GRANT ALL ON TABLE "public"."reporte_ruta" TO "authenticated";
GRANT ALL ON TABLE "public"."reporte_ruta" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reporte_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."reporte_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reporte_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."ruta" TO "anon";
GRANT ALL ON TABLE "public"."ruta" TO "authenticated";
GRANT ALL ON TABLE "public"."ruta" TO "service_role";



GRANT ALL ON TABLE "public"."ruta_parada" TO "anon";
GRANT ALL ON TABLE "public"."ruta_parada" TO "authenticated";
GRANT ALL ON TABLE "public"."ruta_parada" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ruta_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."ruta_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ruta_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."usuario" TO "anon";
GRANT ALL ON TABLE "public"."usuario" TO "authenticated";
GRANT ALL ON TABLE "public"."usuario" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuario_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuario_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuario_sequence" TO "service_role";



GRANT ALL ON TABLE "public"."viaje" TO "anon";
GRANT ALL ON TABLE "public"."viaje" TO "authenticated";
GRANT ALL ON TABLE "public"."viaje" TO "service_role";



GRANT ALL ON TABLE "public"."viaje_parada" TO "anon";
GRANT ALL ON TABLE "public"."viaje_parada" TO "authenticated";
GRANT ALL ON TABLE "public"."viaje_parada" TO "service_role";



GRANT ALL ON TABLE "public"."viaje_ruta" TO "anon";
GRANT ALL ON TABLE "public"."viaje_ruta" TO "authenticated";
GRANT ALL ON TABLE "public"."viaje_ruta" TO "service_role";



GRANT ALL ON SEQUENCE "public"."viaje_sequence" TO "anon";
GRANT ALL ON SEQUENCE "public"."viaje_sequence" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."viaje_sequence" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







