--
-- PostgreSQL database dump
--

\restrict MWdUc5FMkxxe9Hu3gCfmr65dp8WZcyFizGxqy6OjwTn7woMYaRj4tAv7lRdi9h2

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--



ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
BEGIN
  INSERT INTO public.usuario (auth_id, email, nombre, profile_photourl)
  VALUES (
    NEW.id,                                       -- UID from auth.users
    NEW.email,                                    -- email from Google
    NEW.raw_user_meta_data ->> 'full_name',       -- display name from Google
    NEW.raw_user_meta_data ->> 'avatar_url'       -- profile photo from Google
    -- password is left NULL for Google OAuth users
  )
  ON CONFLICT (auth_id) DO NOTHING;
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.handle_new_user() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contrato; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contrato (
    id_contrato integer NOT NULL,
    fecha_fin timestamp(6) without time zone,
    fecha_inicio timestamp(6) without time zone,
    monto integer NOT NULL
);


ALTER TABLE public.contrato OWNER TO postgres;

--
-- Name: contrato_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.contrato_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.contrato_sequence OWNER TO postgres;

--
-- Name: coordenada_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.coordenada_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.coordenada_sequence OWNER TO postgres;

--
-- Name: coordenadas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coordenadas (
    id_coordenada integer NOT NULL,
    latitud double precision,
    longitud double precision,
    sentido character varying(255)
);


ALTER TABLE public.coordenadas OWNER TO postgres;

--
-- Name: coordenadas_ruta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coordenadas_ruta (
    ruta_id integer NOT NULL,
    coordenadas_id integer NOT NULL
);


ALTER TABLE public.coordenadas_ruta OWNER TO postgres;

--
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa (
    id_empresa integer NOT NULL,
    email character varying(255),
    metodo_pago character varying(255),
    name character varying(255),
    pais character varying(255)
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- Name: empresa_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.empresa_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.empresa_sequence OWNER TO postgres;

--
-- Name: file_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.file_data (
    id_image integer NOT NULL,
    file_name character varying(255),
    path character varying(255),
    type character varying(255),
    image_id integer
);


ALTER TABLE public.file_data OWNER TO postgres;

--
-- Name: file_data_id_image_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.file_data ALTER COLUMN id_image ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.file_data_id_image_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interesado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interesado (
    email character varying(255) NOT NULL
);


ALTER TABLE public.interesado OWNER TO postgres;

--
-- Name: interesado_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.interesado_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.interesado_sequence OWNER TO postgres;

--
-- Name: lugar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lugar (
    lugar_id integer NOT NULL,
    descripcion character varying(255),
    direccion character varying(255),
    name character varying(255),
    telefono character varying(255),
    tipo character varying(255),
    url_files character varying(255)[],
    lugar_contrato_id integer,
    lugar_empresa_id integer
);


ALTER TABLE public.lugar OWNER TO postgres;

--
-- Name: lugar_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.lugar_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.lugar_sequence OWNER TO postgres;

--
-- Name: microbus_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.microbus_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.microbus_sequence OWNER TO postgres;

--
-- Name: parada; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parada (
    id_parada integer NOT NULL,
    descripcion_parada character varying(255),
    nombre_parada character varying(255),
    coordenadas_parada_id_coordenada integer
);


ALTER TABLE public.parada OWNER TO postgres;

--
-- Name: parada_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.parada_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.parada_sequence OWNER TO postgres;

--
-- Name: reporte_ruta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reporte_ruta (
    id_reporte_ruta integer NOT NULL,
    descripcion character varying(255),
    like_route integer NOT NULL,
    url_photos character varying(255)[],
    ruta_id integer,
    usuario_id integer
);


ALTER TABLE public.reporte_ruta OWNER TO postgres;

--
-- Name: reporte_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reporte_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reporte_sequence OWNER TO postgres;

--
-- Name: ruta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ruta (
    id_ruta integer NOT NULL,
    active boolean NOT NULL,
    bidirectional boolean DEFAULT true NOT NULL,
    color_ruta character varying(255),
    color_texto_ruta character varying(255),
    horario_ruta character varying(255),
    nombre_corto_ruta character varying(255),
    nombre_ruta character varying(255),
    tipo_ruta character varying(255),
    CONSTRAINT ruta_tipo_ruta_check CHECK (((tipo_ruta)::text = ANY ((ARRAY['URBANA'::character varying, 'SUBURBANA'::character varying, 'PERIFERICA'::character varying, 'COLECTIVO'::character varying, 'MICROBUS'::character varying, 'OTRO'::character varying])::text[])))
);


ALTER TABLE public.ruta OWNER TO postgres;

--
-- Name: ruta_parada; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ruta_parada (
    id_ruta integer NOT NULL,
    id_parada integer NOT NULL
);


ALTER TABLE public.ruta_parada OWNER TO postgres;

--
-- Name: ruta_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ruta_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ruta_sequence OWNER TO postgres;

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id_usuario integer NOT NULL,
    email character varying(255),
    nombre character varying(255),
    password character varying(255),
    profile_photourl character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_sequence OWNER TO postgres;

--
-- Name: viaje; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaje (
    id_viaje integer NOT NULL,
    costo_viaje double precision NOT NULL,
    tiempo_viaje integer NOT NULL
);


ALTER TABLE public.viaje OWNER TO postgres;

--
-- Name: viaje_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaje_usuario (
    id integer NOT NULL,
    id_viaje bigint,
    id_usuario bigint,
    favorito boolean DEFAULT false,
    saved_at date DEFAULT now()
);


ALTER TABLE public.viaje_usuario OWNER TO postgres;

--
-- Name: TABLE viaje_usuario; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.viaje_usuario IS 'Favoritos';


--
-- Name: viaje_Usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viaje_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."viaje_Usuario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viaje_parada; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaje_parada (
    id_viaje integer NOT NULL,
    id_parada integer NOT NULL
);


ALTER TABLE public.viaje_parada OWNER TO postgres;

--
-- Name: viaje_ruta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaje_ruta (
    id_viaje integer NOT NULL,
    id_ruta integer NOT NULL
);


ALTER TABLE public.viaje_ruta OWNER TO postgres;

--
-- Name: viaje_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.viaje_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.viaje_sequence OWNER TO postgres;

--
-- Name: contrato contrato_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT contrato_pkey PRIMARY KEY (id_contrato);


--
-- Name: coordenadas coordenadas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coordenadas
    ADD CONSTRAINT coordenadas_pkey PRIMARY KEY (id_coordenada);


--
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id_empresa);


--
-- Name: file_data file_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_data
    ADD CONSTRAINT file_data_pkey PRIMARY KEY (id_image);


--
-- Name: interesado interesado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interesado
    ADD CONSTRAINT interesado_pkey PRIMARY KEY (email);


--
-- Name: lugar lugar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lugar
    ADD CONSTRAINT lugar_pkey PRIMARY KEY (lugar_id);


--
-- Name: parada parada_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parada
    ADD CONSTRAINT parada_pkey PRIMARY KEY (id_parada);


--
-- Name: reporte_ruta reporte_ruta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte_ruta
    ADD CONSTRAINT reporte_ruta_pkey PRIMARY KEY (id_reporte_ruta);


--
-- Name: ruta ruta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ruta
    ADD CONSTRAINT ruta_pkey PRIMARY KEY (id_ruta);


--
-- Name: parada ukmkrs0w9xcn08tai3ermubgvwt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parada
    ADD CONSTRAINT ukmkrs0w9xcn08tai3ermubgvwt UNIQUE (coordenadas_parada_id_coordenada);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: viaje_usuario viaje_Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_usuario
    ADD CONSTRAINT "viaje_Usuario_pkey" PRIMARY KEY (id);


--
-- Name: viaje viaje_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje
    ADD CONSTRAINT viaje_pkey PRIMARY KEY (id_viaje);


--
-- Name: lugar fk11u76n5iepy6svquy3v72u6h4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lugar
    ADD CONSTRAINT fk11u76n5iepy6svquy3v72u6h4 FOREIGN KEY (lugar_empresa_id) REFERENCES public.empresa(id_empresa);


--
-- Name: coordenadas_ruta fk61plw9sskv924scfc9w8tnei9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coordenadas_ruta
    ADD CONSTRAINT fk61plw9sskv924scfc9w8tnei9 FOREIGN KEY (coordenadas_id) REFERENCES public.coordenadas(id_coordenada);


--
-- Name: ruta_parada fk9sv2hvx3ocwtrs62alemcwhf6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ruta_parada
    ADD CONSTRAINT fk9sv2hvx3ocwtrs62alemcwhf6 FOREIGN KEY (id_parada) REFERENCES public.parada(id_parada);


--
-- Name: coordenadas_ruta fk_coords_ruta_coord; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coordenadas_ruta
    ADD CONSTRAINT fk_coords_ruta_coord FOREIGN KEY (coordenadas_id) REFERENCES public.coordenadas(id_coordenada);


--
-- Name: coordenadas_ruta fk_coords_ruta_ruta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coordenadas_ruta
    ADD CONSTRAINT fk_coords_ruta_ruta FOREIGN KEY (ruta_id) REFERENCES public.ruta(id_ruta);


--
-- Name: file_data fk_file_lugar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.file_data
    ADD CONSTRAINT fk_file_lugar FOREIGN KEY (image_id) REFERENCES public.lugar(lugar_id);


--
-- Name: lugar fk_lugar_contrato; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lugar
    ADD CONSTRAINT fk_lugar_contrato FOREIGN KEY (lugar_contrato_id) REFERENCES public.contrato(id_contrato);


--
-- Name: lugar fk_lugar_empresa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lugar
    ADD CONSTRAINT fk_lugar_empresa FOREIGN KEY (lugar_empresa_id) REFERENCES public.empresa(id_empresa);


--
-- Name: parada fk_parada_coords; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parada
    ADD CONSTRAINT fk_parada_coords FOREIGN KEY (coordenadas_parada_id_coordenada) REFERENCES public.coordenadas(id_coordenada);


--
-- Name: reporte_ruta fk_reporte_ruta; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte_ruta
    ADD CONSTRAINT fk_reporte_ruta FOREIGN KEY (ruta_id) REFERENCES public.ruta(id_ruta);


--
-- Name: reporte_ruta fk_reporte_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte_ruta
    ADD CONSTRAINT fk_reporte_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuario(id_usuario);


--
-- Name: ruta_parada fk_ruta_parada_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ruta_parada
    ADD CONSTRAINT fk_ruta_parada_p FOREIGN KEY (id_parada) REFERENCES public.parada(id_parada);


--
-- Name: ruta_parada fk_ruta_parada_r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ruta_parada
    ADD CONSTRAINT fk_ruta_parada_r FOREIGN KEY (id_ruta) REFERENCES public.ruta(id_ruta);


--
-- Name: viaje_parada fk_viaje_parada_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_parada
    ADD CONSTRAINT fk_viaje_parada_p FOREIGN KEY (id_parada) REFERENCES public.parada(id_parada);


--
-- Name: viaje_parada fk_viaje_parada_v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_parada
    ADD CONSTRAINT fk_viaje_parada_v FOREIGN KEY (id_viaje) REFERENCES public.viaje(id_viaje);


--
-- Name: viaje_ruta fk_viaje_ruta_r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_ruta
    ADD CONSTRAINT fk_viaje_ruta_r FOREIGN KEY (id_ruta) REFERENCES public.ruta(id_ruta);


--
-- Name: viaje_ruta fk_viaje_ruta_v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_ruta
    ADD CONSTRAINT fk_viaje_ruta_v FOREIGN KEY (id_viaje) REFERENCES public.viaje(id_viaje);


--
-- Name: reporte_ruta fkd28t0pheqtn3ebr8uy162jnj5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte_ruta
    ADD CONSTRAINT fkd28t0pheqtn3ebr8uy162jnj5 FOREIGN KEY (ruta_id) REFERENCES public.ruta(id_ruta);


--
-- Name: coordenadas_ruta fkelyn1hjj7w7prb806kwc9sx4b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coordenadas_ruta
    ADD CONSTRAINT fkelyn1hjj7w7prb806kwc9sx4b FOREIGN KEY (ruta_id) REFERENCES public.ruta(id_ruta);


--
-- Name: viaje_parada fkf8dy9470e3y5v1moxbgdxhr93; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_parada
    ADD CONSTRAINT fkf8dy9470e3y5v1moxbgdxhr93 FOREIGN KEY (id_parada) REFERENCES public.parada(id_parada);


--
-- Name: viaje_parada fkishneur6rlpj1m90dbbymjefo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_parada
    ADD CONSTRAINT fkishneur6rlpj1m90dbbymjefo FOREIGN KEY (id_viaje) REFERENCES public.viaje(id_viaje);


--
-- Name: viaje_ruta fkj7f1dv6fu4mc1csfqcqqmeab1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_ruta
    ADD CONSTRAINT fkj7f1dv6fu4mc1csfqcqqmeab1 FOREIGN KEY (id_viaje) REFERENCES public.viaje(id_viaje);


--
-- Name: ruta_parada fkl58bg15ipt86jf2aqpb94v2bf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ruta_parada
    ADD CONSTRAINT fkl58bg15ipt86jf2aqpb94v2bf FOREIGN KEY (id_ruta) REFERENCES public.ruta(id_ruta);


--
-- Name: parada fkl74443u8ed4cirx4xmte9cjf6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parada
    ADD CONSTRAINT fkl74443u8ed4cirx4xmte9cjf6 FOREIGN KEY (coordenadas_parada_id_coordenada) REFERENCES public.coordenadas(id_coordenada);


--
-- Name: viaje_ruta fkrpqihtj1atq5padplnkv0s7rq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaje_ruta
    ADD CONSTRAINT fkrpqihtj1atq5padplnkv0s7rq FOREIGN KEY (id_ruta) REFERENCES public.ruta(id_ruta);


--
-- Name: lugar fkrvi600giiy85kqbjo6n2sarjv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lugar
    ADD CONSTRAINT fkrvi600giiy85kqbjo6n2sarjv FOREIGN KEY (lugar_contrato_id) REFERENCES public.contrato(id_contrato);


--
-- Name: reporte_ruta fksjelqiqfoblq3le2ga7kaig6b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte_ruta
    ADD CONSTRAINT fksjelqiqfoblq3le2ga7kaig6b FOREIGN KEY (usuario_id) REFERENCES public.usuario(id_usuario);


--
-- Name: contrato; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.contrato ENABLE ROW LEVEL SECURITY;

--
-- Name: coordenadas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.coordenadas ENABLE ROW LEVEL SECURITY;

--
-- Name: coordenadas_ruta; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.coordenadas_ruta ENABLE ROW LEVEL SECURITY;

--
-- Name: empresa; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ENABLE ROW LEVEL SECURITY;

--
-- Name: file_data; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.file_data ENABLE ROW LEVEL SECURITY;

--
-- Name: interesado; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.interesado ENABLE ROW LEVEL SECURITY;

--
-- Name: lugar; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.lugar ENABLE ROW LEVEL SECURITY;

--
-- Name: parada; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.parada ENABLE ROW LEVEL SECURITY;

--
-- Name: reporte_ruta; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.reporte_ruta ENABLE ROW LEVEL SECURITY;

--
-- Name: ruta; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ruta ENABLE ROW LEVEL SECURITY;

--
-- Name: ruta_parada; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ruta_parada ENABLE ROW LEVEL SECURITY;

--
-- Name: usuario; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;

--
-- Name: viaje; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.viaje ENABLE ROW LEVEL SECURITY;

--
-- Name: viaje_parada; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.viaje_parada ENABLE ROW LEVEL SECURITY;

--
-- Name: viaje_ruta; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.viaje_ruta ENABLE ROW LEVEL SECURITY;

--
-- Name: viaje_usuario; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.viaje_usuario ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: FUNCTION handle_new_user(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.handle_new_user() TO anon;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;


--
-- Name: TABLE contrato; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.contrato TO anon;
GRANT ALL ON TABLE public.contrato TO authenticated;
GRANT ALL ON TABLE public.contrato TO service_role;


--
-- Name: SEQUENCE contrato_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.contrato_sequence TO anon;
GRANT ALL ON SEQUENCE public.contrato_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.contrato_sequence TO service_role;


--
-- Name: SEQUENCE coordenada_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.coordenada_sequence TO anon;
GRANT ALL ON SEQUENCE public.coordenada_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.coordenada_sequence TO service_role;


--
-- Name: TABLE coordenadas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.coordenadas TO anon;
GRANT ALL ON TABLE public.coordenadas TO authenticated;
GRANT ALL ON TABLE public.coordenadas TO service_role;


--
-- Name: TABLE coordenadas_ruta; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.coordenadas_ruta TO anon;
GRANT ALL ON TABLE public.coordenadas_ruta TO authenticated;
GRANT ALL ON TABLE public.coordenadas_ruta TO service_role;


--
-- Name: TABLE empresa; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.empresa TO anon;
GRANT ALL ON TABLE public.empresa TO authenticated;
GRANT ALL ON TABLE public.empresa TO service_role;


--
-- Name: SEQUENCE empresa_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.empresa_sequence TO anon;
GRANT ALL ON SEQUENCE public.empresa_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.empresa_sequence TO service_role;


--
-- Name: TABLE file_data; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.file_data TO anon;
GRANT ALL ON TABLE public.file_data TO authenticated;
GRANT ALL ON TABLE public.file_data TO service_role;


--
-- Name: SEQUENCE file_data_id_image_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.file_data_id_image_seq TO anon;
GRANT ALL ON SEQUENCE public.file_data_id_image_seq TO authenticated;
GRANT ALL ON SEQUENCE public.file_data_id_image_seq TO service_role;


--
-- Name: TABLE interesado; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.interesado TO anon;
GRANT ALL ON TABLE public.interesado TO authenticated;
GRANT ALL ON TABLE public.interesado TO service_role;


--
-- Name: SEQUENCE interesado_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.interesado_sequence TO anon;
GRANT ALL ON SEQUENCE public.interesado_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.interesado_sequence TO service_role;


--
-- Name: TABLE lugar; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.lugar TO anon;
GRANT ALL ON TABLE public.lugar TO authenticated;
GRANT ALL ON TABLE public.lugar TO service_role;


--
-- Name: SEQUENCE lugar_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.lugar_sequence TO anon;
GRANT ALL ON SEQUENCE public.lugar_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.lugar_sequence TO service_role;


--
-- Name: SEQUENCE microbus_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.microbus_sequence TO anon;
GRANT ALL ON SEQUENCE public.microbus_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.microbus_sequence TO service_role;


--
-- Name: TABLE parada; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.parada TO anon;
GRANT ALL ON TABLE public.parada TO authenticated;
GRANT ALL ON TABLE public.parada TO service_role;


--
-- Name: SEQUENCE parada_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.parada_sequence TO anon;
GRANT ALL ON SEQUENCE public.parada_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.parada_sequence TO service_role;


--
-- Name: TABLE reporte_ruta; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.reporte_ruta TO anon;
GRANT ALL ON TABLE public.reporte_ruta TO authenticated;
GRANT ALL ON TABLE public.reporte_ruta TO service_role;


--
-- Name: SEQUENCE reporte_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.reporte_sequence TO anon;
GRANT ALL ON SEQUENCE public.reporte_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.reporte_sequence TO service_role;


--
-- Name: TABLE ruta; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ruta TO anon;
GRANT ALL ON TABLE public.ruta TO authenticated;
GRANT ALL ON TABLE public.ruta TO service_role;


--
-- Name: TABLE ruta_parada; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ruta_parada TO anon;
GRANT ALL ON TABLE public.ruta_parada TO authenticated;
GRANT ALL ON TABLE public.ruta_parada TO service_role;


--
-- Name: SEQUENCE ruta_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.ruta_sequence TO anon;
GRANT ALL ON SEQUENCE public.ruta_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.ruta_sequence TO service_role;


--
-- Name: TABLE usuario; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.usuario TO anon;
GRANT ALL ON TABLE public.usuario TO authenticated;
GRANT ALL ON TABLE public.usuario TO service_role;


--
-- Name: SEQUENCE usuario_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.usuario_sequence TO anon;
GRANT ALL ON SEQUENCE public.usuario_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.usuario_sequence TO service_role;


--
-- Name: TABLE viaje; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.viaje TO anon;
GRANT ALL ON TABLE public.viaje TO authenticated;
GRANT ALL ON TABLE public.viaje TO service_role;


--
-- Name: TABLE viaje_usuario; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.viaje_usuario TO anon;
GRANT ALL ON TABLE public.viaje_usuario TO authenticated;
GRANT ALL ON TABLE public.viaje_usuario TO service_role;


--
-- Name: SEQUENCE "viaje_Usuario_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."viaje_Usuario_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."viaje_Usuario_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."viaje_Usuario_id_seq" TO service_role;


--
-- Name: TABLE viaje_parada; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.viaje_parada TO anon;
GRANT ALL ON TABLE public.viaje_parada TO authenticated;
GRANT ALL ON TABLE public.viaje_parada TO service_role;


--
-- Name: TABLE viaje_ruta; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.viaje_ruta TO anon;
GRANT ALL ON TABLE public.viaje_ruta TO authenticated;
GRANT ALL ON TABLE public.viaje_ruta TO service_role;


--
-- Name: SEQUENCE viaje_sequence; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.viaje_sequence TO anon;
GRANT ALL ON SEQUENCE public.viaje_sequence TO authenticated;
GRANT ALL ON SEQUENCE public.viaje_sequence TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict MWdUc5FMkxxe9Hu3gCfmr65dp8WZcyFizGxqy6OjwTn7woMYaRj4tAv7lRdi9h2

