SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- 1. SCHEMA SETUP
CREATE SCHEMA IF NOT EXISTS "public";
ALTER SCHEMA "public" OWNER TO "pg_database_owner";
COMMENT ON SCHEMA "public" IS 'standard public schema';

SET default_tablespace = '';
SET default_table_access_method = "heap";

-- 2. SEQUENCES
CREATE SEQUENCE IF NOT EXISTS "public"."contrato_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."coordenada_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."empresa_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."interesado_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."lugar_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."microbus_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."parada_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."reporte_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."ruta_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."usuario_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS "public"."viaje_sequence" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- 3. TABLES

CREATE TABLE IF NOT EXISTS "public"."contrato" (
                                                   "id_contrato" integer NOT NULL,
                                                   "fecha_fin" timestamp(6) without time zone,
    "fecha_inicio" timestamp(6) without time zone,
    "monto" integer NOT NULL,
    CONSTRAINT "contrato_pkey" PRIMARY KEY ("id_contrato")
    );

CREATE TABLE IF NOT EXISTS "public"."coordenadas" (
                                                      "id_coordenada" integer NOT NULL,
                                                      "latitud" double precision,
                                                      "longitud" double precision,
                                                      CONSTRAINT "coordenadas_pkey" PRIMARY KEY ("id_coordenada")
    );

CREATE TABLE IF NOT EXISTS "public"."ruta" (
                                               "id_ruta" integer NOT NULL,
                                               "active" boolean NOT NULL,
                                               "horario_ruta" character varying(255),
    "nombre_ruta" character varying(255),
    "color_ruta" character varying(255),
    "color_texto_ruta" character varying(255),
    "nombre_corto_ruta" character varying(255),
    "tipo_ruta" character varying(255),
    CONSTRAINT "ruta_pkey" PRIMARY KEY ("id_ruta")
    );

CREATE TABLE IF NOT EXISTS "public"."coordenadas_ruta" (
                                                           "ruta_id" integer NOT NULL,
                                                           "coordenadas_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."empresa" (
                                                  "id_empresa" integer NOT NULL,
                                                  "email" character varying(255),
    "metodo_pago" character varying(255),
    "name" character varying(255),
    "pais" character varying(255),
    CONSTRAINT "empresa_pkey" PRIMARY KEY ("id_empresa")
    );

CREATE TABLE IF NOT EXISTS "public"."lugar" (
                                                "lugar_id" integer NOT NULL,
                                                "descripcion" character varying(255),
    "name" character varying(255),
    "telefono" character varying(255),
    "tipo" character varying(255),
    "lugar_contrato_id" integer,
    "lugar_empresa_id" integer,
    "url_files" character varying(255)[],
    CONSTRAINT "lugar_pkey" PRIMARY KEY ("lugar_id")
    );

CREATE TABLE IF NOT EXISTS "public"."file_data" (
                                                    "id_image" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                    "file_name" character varying(255),
    "path" character varying(255),
    "type" character varying(255),
    "image_id" integer,
    CONSTRAINT "file_data_pkey" PRIMARY KEY ("id_image")
    );

CREATE TABLE IF NOT EXISTS "public"."interesado" (
                                                     "email" character varying(255) NOT NULL,
    CONSTRAINT "interesado_pkey" PRIMARY KEY ("email")
    );

CREATE TABLE IF NOT EXISTS "public"."parada" (
                                                 "id_parada" integer NOT NULL,
                                                 "nombre_parada" character varying(255),
    "coordenadas_parada_id_coordenada" integer,
    "descripcion_parada" character varying(255),
    CONSTRAINT "parada_pkey" PRIMARY KEY ("id_parada"),
    CONSTRAINT "uk_parada_coords" UNIQUE ("coordenadas_parada_id_coordenada")
    );

CREATE TABLE IF NOT EXISTS "public"."usuario" (
                                                  "id_usuario" integer NOT NULL,
                                                  "email" character varying(255),
    "nombre" character varying(255),
    "password" character varying(255),
    "profile_photourl" character varying(255),
    CONSTRAINT "usuario_pkey" PRIMARY KEY ("id_usuario")
    );

CREATE TABLE IF NOT EXISTS "public"."reporte_ruta" (
                                                       "id_reporte_ruta" integer NOT NULL,
                                                       "descripcion" character varying(255),
    "like_route" integer NOT NULL,
    "ruta_id" integer,
    "usuario_id" integer,
    "url_photos" character varying(255)[],
    CONSTRAINT "reporte_ruta_pkey" PRIMARY KEY ("id_reporte_ruta")
    );

CREATE TABLE IF NOT EXISTS "public"."ruta_parada" (
                                                      "id_ruta" integer NOT NULL,
                                                      "id_parada" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."viaje" (
                                                "id_viaje" integer NOT NULL,
                                                "costo_viaje" double precision NOT NULL,
                                                "tiempo_viaje" integer NOT NULL,
                                                CONSTRAINT "viaje_pkey" PRIMARY KEY ("id_viaje")
    );

CREATE TABLE IF NOT EXISTS "public"."viaje_parada" (
                                                       "id_viaje" integer NOT NULL,
                                                       "id_parada" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."viaje_ruta" (
                                                     "id_viaje" integer NOT NULL,
                                                     "id_ruta" integer NOT NULL
);

-- 4. FOREIGN KEYS
ALTER TABLE ONLY "public"."lugar" ADD CONSTRAINT "fk_lugar_empresa" FOREIGN KEY ("lugar_empresa_id") REFERENCES "public"."empresa"("id_empresa");
ALTER TABLE ONLY "public"."lugar" ADD CONSTRAINT "fk_lugar_contrato" FOREIGN KEY ("lugar_contrato_id") REFERENCES "public"."contrato"("id_contrato");
ALTER TABLE ONLY "public"."coordenadas_ruta" ADD CONSTRAINT "fk_coords_ruta_coord" FOREIGN KEY ("coordenadas_id") REFERENCES "public"."coordenadas"("id_coordenada");
ALTER TABLE ONLY "public"."coordenadas_ruta" ADD CONSTRAINT "fk_coords_ruta_ruta" FOREIGN KEY ("ruta_id") REFERENCES "public"."ruta"("id_ruta");
ALTER TABLE ONLY "public"."file_data" ADD CONSTRAINT "fk_file_lugar" FOREIGN KEY ("image_id") REFERENCES "public"."lugar"("lugar_id");
ALTER TABLE ONLY "public"."ruta_parada" ADD CONSTRAINT "fk_ruta_parada_p" FOREIGN KEY ("id_parada") REFERENCES "public"."parada"("id_parada");
ALTER TABLE ONLY "public"."ruta_parada" ADD CONSTRAINT "fk_ruta_parada_r" FOREIGN KEY ("id_ruta") REFERENCES "public"."ruta"("id_ruta");
ALTER TABLE ONLY "public"."reporte_ruta" ADD CONSTRAINT "fk_reporte_ruta" FOREIGN KEY ("ruta_id") REFERENCES "public"."ruta"("id_ruta");
ALTER TABLE ONLY "public"."reporte_ruta" ADD CONSTRAINT "fk_reporte_usuario" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuario"("id_usuario");
ALTER TABLE ONLY "public"."viaje_parada" ADD CONSTRAINT "fk_viaje_parada_p" FOREIGN KEY ("id_parada") REFERENCES "public"."parada"("id_parada");
ALTER TABLE ONLY "public"."viaje_parada" ADD CONSTRAINT "fk_viaje_parada_v" FOREIGN KEY ("id_viaje") REFERENCES "public"."viaje"("id_viaje");
ALTER TABLE ONLY "public"."viaje_ruta" ADD CONSTRAINT "fk_viaje_ruta_v" FOREIGN KEY ("id_viaje") REFERENCES "public"."viaje"("id_viaje");
ALTER TABLE ONLY "public"."viaje_ruta" ADD CONSTRAINT "fk_viaje_ruta_r" FOREIGN KEY ("id_ruta") REFERENCES "public"."ruta"("id_ruta");
ALTER TABLE ONLY "public"."parada" ADD CONSTRAINT "fk_parada_coords" FOREIGN KEY ("coordenadas_parada_id_coordenada") REFERENCES "public"."coordenadas"("id_coordenada");

-- 5. RLS (Row Level Security) - Enabled but policies must be defined separately
ALTER TABLE "public"."contrato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."coordenadas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."coordenadas_ruta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."empresa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."interesado" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lugar" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."parada" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reporte_ruta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ruta" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."ruta_parada" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."usuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."viaje" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."viaje_parada" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."viaje_ruta" ENABLE ROW LEVEL SECURITY;